version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=apidb
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /code/.venv
    command: >
      bash -c "sleep 1
      && poetry run alembic upgrade head
      && poetry run uvicorn --host 0.0.0.0 --port 8000 app.main:app --reload"
    depends_on:
      - apidb
  apidb:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
