"""add contact

Revision ID: 1dd720033bbe
Revises: 0594dfba7608
Create Date: 2023-11-27 21:08:17.469503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1dd720033bbe"
down_revision: Union[str, None] = "0594dfba7608"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Contact",
        sa.Column("firstname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lastname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patronymic", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("telegram_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["Company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Contact")
    # ### end Alembic commands ###
