"""update contact phone field

Revision ID: ae58a567e400
Revises: 1dd720033bbe
Create Date: 2023-11-28 19:42:53.455254

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae58a567e400"
down_revision: Union[str, None] = "1dd720033bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Contact",
        "phone_number",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="phone_number::integer",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Contact",
        "phone_number",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
