"""add created_by field

Revision ID: b48f805d57d3
Revises: 3c4d5a381326
Create Date: 2023-12-02 20:35:51.609572

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b48f805d57d3"
down_revision: Union[str, None] = "3c4d5a381326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Company",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "Contact",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Contact", "created_by")
    op.drop_column("Company", "created_by")
    # ### end Alembic commands ###
